### PR TITLE
Merge feature/google-login to develop

### PR DESCRIPTION
**Pull request by teddyotieno**
**What does this PR do?**

Implement google-sign for authentication, rather than email/password.

### CODE REVIEW

**Comment by teddyotieno** [comment]
I'm on left with refactoring the code.

**Comment by judithachieng** [comment]
screen shot 2017-11-23 at 12 22 39 pm
 I get this error if while trying to sign in, there should be a check to see if the user already exists

**Comment by teddyotieno** [comment]
Fixed the above issues.

**Comment by josephbosire** [comment]
Let's fix the merge conflicts then we can proceed to merge this branch

**Pull request merged**
